name: wasm_ffi
description: A wrapper for wasm which can be used as a drop-in replacement for dart:ffi for Web platform.
version: 2.1.0
repository: https://github.com/vm75/wasm_ffi

environment:
  sdk: ^3.6.0

dependencies:
  ffi: ^2.1.3
  http: ^1.2.2
  meta: ^1.15.0
  path: ^1.9.0
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.8
  build_test: ^2.2.2
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
  test: ^1.25.12

topics:
 - ffi
 - wasm
 - native
 - web

platforms:
  web:
