name: example_flutter
description: "Example Flutter project for wasm_ffi"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.8

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  wasm_ffi:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
