// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'package:wasm_ffi/ffi.dart' as ffi;

/// Bindings for Native Example.
class NativeExampleBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeExampleBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeExampleBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// library name
  ffi.Pointer<ffi.Char> getLibraryName() {
    return _getLibraryName();
  }

  late final _getLibraryNamePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'getLibraryName');
  late final _getLibraryName =
      _getLibraryNamePtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// hello world
  ffi.Pointer<ffi.Char> hello(
    ffi.Pointer<ffi.Char> text,
  ) {
    return _hello(
      text,
    );
  }

  late final _helloPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>('hello');
  late final _hello = _helloPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  /// free up the memory allocated by the library
  void freeMemory(
    ffi.Pointer<ffi.Char> buffer,
  ) {
    return _freeMemory(
      buffer,
    );
  }

  late final _freeMemoryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'freeMemory');
  late final _freeMemory =
      _freeMemoryPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// size of an int
  int intSize() {
    return _intSize();
  }

  late final _intSizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('intSize');
  late final _intSize = _intSizePtr.asFunction<int Function()>();

  /// size of a bool
  int boolSize() {
    return _boolSize();
  }

  late final _boolSizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('boolSize');
  late final _boolSize = _boolSizePtr.asFunction<int Function()>();

  /// size of a pointer
  int pointerSize() {
    return _pointerSize();
  }

  late final _pointerSizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('pointerSize');
  late final _pointerSize = _pointerSizePtr.asFunction<int Function()>();

  TestStruct updateStruct(
    TestStruct s,
  ) {
    return _updateStruct(
      s,
    );
  }

  late final _updateStructPtr =
      _lookup<ffi.NativeFunction<TestStruct Function(TestStruct)>>(
          'updateStruct');
  late final _updateStruct =
      _updateStructPtr.asFunction<TestStruct Function(TestStruct)>();

  TestUnion updateUnion(
    TestUnion u,
  ) {
    return _updateUnion(
      u,
    );
  }

  late final _updateUnionPtr =
      _lookup<ffi.NativeFunction<TestUnion Function(TestUnion)>>('updateUnion');
  late final _updateUnion =
      _updateUnionPtr.asFunction<TestUnion Function(TestUnion)>();
}

final class TestStruct extends ffi.Struct {
  static final size = 10;
  static final alignment = 1;
  static final packed = true;
  static final fields = [
    {
      'name': 's',
      'type': 'int',
      'offset': 0,
      'size': 2,
    },
    {
      'name': 'a',
      'type': 'char[5]',
      'offset': 2,
      'size': 5,
    },
    {
      'name': 'i',
      'type': 'int',
      'offset': 7,
      'size': 4,
    },
  ];

  int get s =>
  ffi.Array<ffi.Char> a;
  int i;
}

final class TestUnion extends ffi.Union {
  external TestStruct s;

  @ffi.Array.multi([10])
  external ffi.Array<ffi.Char> a;
}
