name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          channel: stable
      - run: dart pub get
      - run: dart analyze
      - run: dart test -p chrome
      - run: dart test --compiler=dart2wasm
